ppw_story/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from story_4.views import index as home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='index'),
    url(r'^web/', include('story_4.urls', namespace='web')),
    url(r'^schedule/', include('story_5.urls', namespace='schedule')),
]

story_1/urls.py
from django.conf.urls import url

from .views import index, friend_profile

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^friend_profile/$', friend_profile, name='friend_profile')
]

story_4/urls.py
from django.conf.urls import url

from .views import about, blog, contact, guest_book, index, lpj_page, rumbuk_page

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^about/$', about, name='about'),
    url(r'^blog/$', blog, name='blog'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^guest-book/$', guest_book, name='guest-book'),
    url(r'^project/lpj/', lpj_page, name='lpj'),
    url(r'^project/rumbuk/', rumbuk_page, name='rumbuk'),
]

story_5/urls.py
from django.conf.urls import url
from .views import ScheduleCreate, ScheduleList, delete_all_schedules

urlpatterns = [
    url(r'^create/$', ScheduleCreate.as_view(), name='schedule-form'),
    url(r'^list/$', ScheduleList.as_view(), name='schedule-list'),
    url(r'^delete/$', delete_all_schedules, name='schedule-delete')
]

story_1/models.py
from django.db import models

# Create your models here.

story_4/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class JadwalPribadi(models.Model):
    name = models.CharField(default='', max_length=30,
                            validators=[MaxLengthValidator(30)])
    place = models.CharField(default='', max_length=30,
                             validators=[MaxLengthValidator(30)])
    category = models.CharField(null=True, blank=True, default='', max_length=30,
                                validators=[MaxLengthValidator(30)])
    time = models.DateTimeField()

    class Meta:
        verbose_name_plural = 'Jadwal Pribadi'

    def __str__(self):
        return self.name

story_5/forms.py
from django import forms

from .models import JadwalPribadi


class JadwalForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(JadwalForm, self).__init__(*args, **kwargs)

        self.fields['name'].label = 'Nama Kegiatan'
        self.fields['name'].widget.attrs = {'class': 'form-control', 'placeholder': 'Masukkan nama kegiatan'}
        self.fields['name'].error_messages = {'max_length': 'Maksimal karakter adalah 30 karakter.'}

        self.fields['place'].label = 'Tempat Kegiatan'
        self.fields['place'].widget.attrs = {'class': 'form-control', 'placeholder': 'Masukkan tempat kegiatan'}
        self.fields['place'].error_messages = {'max_length': 'Maksimal karakter adalah 30 karakter.'}

        self.fields['category'].label = 'Kategori Kegiatan'
        self.fields['category'].widget.attrs = {'class': 'form-control', 'placeholder': 'Masukkan kategori kegiatan'}
        self.fields['category'].error_messages = {'max_length': 'Maksimal karakter adalah 30 karakter.'}

        self.fields['time'] = forms.DateTimeField(
            widget=forms.DateTimeInput(
                attrs={'class': 'form-control',
                       'type': 'datetime-local'}),
            label='Jadwal Kegiatan',
            input_formats=['%Y-%d-%mT%H:%M'],
            error_messages={'invalid': 'Format tanggal dan waktu tidak valid.'})

    class Meta:
        model = JadwalPribadi
        fields = ['name', 'place', 'category', 'time']

story_1/views.py
from datetime import date

from django.shortcuts import render

from .utils import birth_date, calculate_age

response = {}


def index(request):
    return render(request, 'index.html', {'name': 'Farhan Azyumardhi Azmi',
                                          'npm': 170697934,
                                          'age': calculate_age(birth_date.year),
                                          'kuliah': 'University of Indonesia'})


def friend_profile(request):
    response['nuga_name'] = 'Muhammad Ardivan Nugroho Satrio'
    response['nuga_npm'] = 1706025371
    response['nuga_age'] = calculate_age(date(1999, 8, 14).year)
    response['nuga_hobby'] = 'make jokes'
    response['sayid_name'] = 'Sayid Abyan Rizal Shiddiq'
    response['sayid_npm'] = 1706022445
    response['sayid_age'] = calculate_age(date(1999, 7, 21).year)
    response['sayid_hobby'] = 'watch anime'
    return render(request, 'friends_profile.html', response)

story_4/views.py
from django.shortcuts import render


def index(request):
    html = 'index.html'
    return render(request, html)


def about(request):
    html = 'about.html'
    return render(request, html)


def blog(request):
    html = 'blog.html'
    return render(request, html)


def contact(request):
    html = 'contact.html'
    return render(request, html)


def guest_book(request):
    html = 'guest-book.html'
    return render(request, html)


def lpj_page(request):
    html = 'lpj.html'
    return render(request, html)


def rumbuk_page(request):
    html = 'rumbuk.html'
    return render(request, html)

story_5/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, ListView

from .forms import JadwalForm
from .models import JadwalPribadi


class ScheduleCreate(CreateView):
    model = JadwalPribadi
    form_class = JadwalForm
    template_name = 'schedule-form.html'

    def get_success_url(self):
        return reverse('schedule:schedule-list')


class ScheduleList(ListView):
    model = JadwalPribadi
    template_name = 'schedule-list.html'
    context_object_name = 'schedule'
    queryset = JadwalPribadi.objects.all()


def delete_all_schedules(request):
    JadwalPribadi.objects.all().delete()
    return HttpResponseRedirect(reverse('schedule:schedule-list'))

story_1/templates/friends_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>My Friends</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/friends_profile.css' %}">
</head>
<body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column" id="sayid_profile">
        <div class="sayid-image">
            <img id="sayid-image" src="{% static 'images/sayid.jpg' %}" alt="sayid's photo">
        </div>
        <span class="lead sayid-description border">
            <article> His name is {{ sayid_name }}. </article>
            <article> His age is {{ sayid_age }}.</article>
            <article> He's currently studying as a computer science student at University of Indonesia.
                with student number {{ sayid_npm }}.</article>
            <article> He likes to {{ sayid_hobby }}. </article>
            <a href="{% url 'story_1:index' %}">Back to my profile</a> <br>
        </span>
    </div>

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column" id="nuga_profile">
        <div class="nuga-image">
            <img id="nuga-image" src="{% static 'images/nuga.jpg' %}" alt="nuga's photo">
        </div>
        <span class="lead nuga-description border">
            <article> His name is {{ nuga_name }}. </article>
            <article> His age is {{ nuga_age }}.</article>
            <article> He's currently studying as a computer science student at University of Indonesia.
                with student number {{ nuga_npm }}.</article>
            <article> He likes to {{ nuga_hobby }}. </article>
            <a href="{% url 'story_1:index' %}">Back to my profile</a> <br>
        </span>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

story_1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About Me</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/story_1_index.css' %}">
</head>
<body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <div class="image">
            <img class="my-image" src="{% static 'images/farhan.JPG' %}" alt="My photo">
        </div>
        <span class="lead description border">
            <article> My name is {{ name }}. </article>
            <article> I'm currently studying as a computer science student at {{ kuliah }} with student number {{ npm }}.</article>
            <article> I'm into is gaming. </article>
            <article> I prefer back-end than front-end. Sorry, lads. </article>
        </span>
        <a class="lead" id="profile_link" href="{% url 'story_1:friend_profile' %}">My Friends</a>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

story_4/templates/about.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - About
    {% endblock title %}

    {% block content %}
        <div class="main-div">
            <div class="image-div">
                <img class="mx-auto d-block avatar-image" src="{% static 'images/self.JPG' %}">
            </div>

            <div>
                <h1 class="text-main">Know Me Deeper</h1>
            </div>

            <div class="bio-desc mx-auto d-block">
                <h4 class="text-sub">Hello, I am Farhan Azyumardhi Azmi.</h4>
                <h4 class="text-sub">I’m currently studying Computer Science Major at University of Indonesia.</h4>
                <h4 class="text-sub">I like to learn new opportunities.</h4>
            </div>

            <div class="border-line-main"></div>

            <div>
                <h1 class="academic-text">Academic History</h1>
            </div>

            <div class="container mx-auto d-block academic-div">
                <div class="row">
                    <div class="col">
                        <a class="ui-logo academic-logo" title="ui-logo"></a>
                    </div>
                    <div class="col academic-desc">
                        <p>Universitas Indonesia</p>
                        <p>Computer Science Major</p>
                        <p>2017 - Current</p>
                    </div>
                </div>
            </div>

            <div class="border-line-sub"></div>

            <div class="container mx-auto d-block academic-div">
                <div class="row">
                    <div class="col">
                        <a class="sma-logo academic-logo" title="sma-logo"></a>
                    </div>
                    <div class="col academic-desc">
                        <p>SMAN 49 Jakarta</p>
                        <p>2014 - 2017</p>
                    </div>
                </div>
            </div>

            <div class="border-line-main"></div>

            <div>
                <h1 class="work-text">Work Experience</h1>
            </div>

            <div class="container mx-auto d-block project-div">
                <div class="row">
                    <div class="col">
                        <a class="fuki-logo project-logo" title="fuki-logo"></a>
                    </div>
                    <div class="col project-desc">
                        <p>FUKI Fasilkom UI 2018</p>
                        <p>IT Force Bureau Staff</p>
                    </div>
                </div>
            </div>

            <div class="border-line-main"></div>

            <div class="container mx-auto d-block skill-div">
                <h1>Skills</h1>
            </div>

            <div class="container skill-logo-div" style="margin-bottom: 20px;">
                <div class="row">
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/python.png' %}" width="200px" height="200px" alt="python-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/java.png' %}" width="200px" height="200px" alt="java-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/django.png' %}" width="200px" height="200px" alt="django-logo">
                    </div>
                    <div class="col">
                        <img class="skill-img" src="{% static 'images/HTML5_Badge_256.png' %}" width="200px" height="200px" alt="html-logo">
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</html>

story_4/templates/blog.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - Blog
    {% endblock title %}

    {% block content %}
        <div class="main-div">
            <div>
                <h1 class="text-main">Blog</h1>
            </div>

            <div class="container mx-auto d-block article-div">
                <div class="row">
                    <div class="col">
                        <img class="article-cover" src="{% static 'images/programming_language.jpeg' %}" alt="programming-language"
                        width="320px" height="200px">
                    </div>
                    <div class="col article-desc">
                        <h3>Best Programming Languages To Learn In 2018</h3>
                        <a href="#"><h4>Read the full story</h4></a>
                    </div>
                </div>
            </div>

            <div class="container mx-auto d-block article-div">
                <div class="row">
                    <div class="col">
                        <img class="article-cover" src="{% static 'images/videogames.jpg' %}" alt="video-game">
                    </div>
                    <div class="col article-desc">
                        <h3>Best Video Games To Play In 2018</h3>
                        <a href="#"><h4>Read the full story</h4></a>
                    </div>
                </div>
            </div>

        </div>
    {% endblock content %}
</html>

story_4/templates/contact.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - Contact Me
    {% endblock %}

    {% block content %}
        <div class="main-div">
            <div>
                <h1 class="text-main">Contact Me</h1>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block">
                    <div class="form-group">
                        <label for="input-name" class="form-label">Nama Anda</label>
                        <input class="form-control" id="input-name" placeholder="Masukkan nama Anda">
                        <label for="input-email" class="form-label">Email Anda</label>
                        <input class="form-control" id="input-email" aria-describedby="emailHelp" placeholder="Masukkan email Anda" type="email">
                        <label for="input-subject" class="form-label">Subjek Pesan</label>
                        <input class="form-control" id="input-subject" placeholder="Masukkan subjek pesan" type="text">
                        <label for="input-message" class="form-label">Pesan Anda</label>
                        <textarea class="form-control" id="input-message" type="text" placeholder="Masukkan pesan Anda"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Kirim Pesan</button>
                </form>
            </div>
        </div>
    {% endblock %}
</html>

story_4/templates/guest-book.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - Guest Book
    {% endblock title %}

    {% block content %}
        <div class="main-div">
            <div>
                <h1 class="text-main">Guest Book</h1>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block">
                    <div class="form-group">
                        <label for="input-name" class="form-label">Nama Anda</label>
                        <input class="form-control" id="input-name" placeholder="Masukkan nama Anda">
                        <label for="input-date" class="form-label">Tanggal</label>
                        <input class="form-control" id="input-date" type="date">
                        <label for="input-email" class="form-label">Email Anda</label>
                        <input class="form-control" id="input-email" aria-describedby="emailHelp" placeholder="Masukkan email Anda" type="email">
                        <label for="input-subject" class="form-label">Subjek Pesan</label>
                        <input class="form-control" id="input-subject" placeholder="Masukkan subjek pesan" type="text">
                        <label for="input-message" class="form-label">Pesan Anda</label>
                        <textarea class="form-control" id="input-message" type="textarea" placeholder="Masukkan pesan Anda"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Kirim Pesan</button>
                </form>
            </div>
        </div>
    {% endblock content %}
</html>

story_4/templates/index.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block content %}
        <div class="main-div">
            <div class="image-div">
                <img class="mx-auto d-block jumbotron-image" src="{% static 'images/jumbotron.png' %}">
            </div>

            <div class="border-line-main"></div>

            <div>
                <h1 class="text-main">Welcome To My Website</h1>
                <h3 class="text-sub">I'm Farhan, an aspiring web developer from Jakarta.</h3>
            </div>

            <div class="border-line-main"></div>

            <div>
                <h1 class="projects-text">My Projects</h1>
            </div>

            <div class="border-line-sub"></div>

            <div class="container mx-auto d-block project-div">
                <div class="row">
                    <div class="col">
                        <a class="fuki-logo project-logo" href="{% url 'web:lpj' %}" title="fuki-logo"></a>
                    </div>
                    <div class="col project-desc">
                        LPJ Online FUKI Fasilkom UI 2018
                    </div>
                </div>
        </div>

        <div class="border-line-sub"></div>

        <div class="container mx-auto d-block project-div">
            <div class="row">
                <div class="col">
                    <a class="rumbuk-logo project-logo" href="{% url 'web:rumbuk' %}" title="rumbuk-logo"></a>
                </div>
                <div class="col project-desc">
                    Rumah Buku FUKI Fasilkom UI 2018
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</html>

story_4/templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="landing page">
        <meta name="author" content="Farhan Azyumardhi Azmi - 1706979234">

        <title>
            {% block title %}
                Farhan Azmi - Index
            {% endblock title %}
        </title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/story_3.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Bitter|Chivo|Montserrat" rel="stylesheet">

    </head>

    <body>
        <header>
            {% include 'layout/header.html' %}
        </header>

        <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock content %}
        </content>

        <footer>
            {% include 'layout/footer.html' %}
        </footer>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

story_4/templates/layout/footer.html
<!DOCTYPE html>
<html lang="en">
        <div class="border-line-main"></div>
        <div class="row contacts">
            <div class="col">
                <a class="linkedin-logo contact-logo" href="https://www.linkedin.com/in/farhan-azyumardhi-azmi/" title="linkedin-logo"></a>
                <a class="gitlab-logo contact-logo" href="https://gitlab.com/ZoneZ" title="gitlab-logo"></a>
            </div>
        </div>
</html>

story_4/templates/layout/header.html
<!DOCTYPE html>
<html lang="en">
    <nav class="navbar navbar-expand-lg main-navbar">
        <a class="navbar-brand navbar-button" href="{% url 'web:index' %}">Home</a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item navbar-button">
                    <a class="nav-link" href="{% url 'web:about' %}">About Me</a>
                </li>
                <li class="nav-item navbar-button">
                    <a class="nav-link" href="{% url 'web:blog' %}">Blog</a>
                </li>
                <li class="nav-item navbar-button">
                    <a class="nav-link" href="{% url 'web:contact' %}">Contact Me</a>
                </li>
                <li class="nav-item navbar-button">
                    <a class="nav-link" href="{% url 'web:guest-book' %}">Guest Book</a>
                </li>
                <li class="nav-item navbar-button">
                    <a class="nav-link" href="{% url 'schedule:schedule-form' %}">Schedule Form</a>
                </li>
                <li class="nav-item navbar-button">
                    <a class="nav-link" href="{% url 'schedule:schedule-list' %}">Schedule List</a>
                </li>
            </ul>
        </div>
    </nav>
</html>

story_4/templates/lpj.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - LPJ Online
    {% endblock title %}

    {% block content %}
        <div class="main-div">
            <div>
                <h1 class="text-main">LPJ Online Fasilkom UI</h1>
            </div>

            <div class="border-line-sub"></div>

            <div class="container mx-auto d-block" style="margin: 20px;">
                <div class="row">
                    <div class="col">
                        <img class="lpj-image" src="{% static 'images/static_lpj_images_logo-fuki.png' %}" alt="fuki-logo">
                    </div>
                    <div class="col project-desc">
                        <p>Online LPJ website for FUKI Fasilkom UI.</p>
                        <p>I worked as...</p>
                        <p><em><u>Back-End Developer</u></em></p>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</html>

story_4/templates/rumbuk.html
{% extends 'layout/base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    {% block title %}
        Farhan Azmi - Rumbuk
    {% endblock %}

    {% block content %}
        <div class="main-div">
            <div>
                <h1 class="text-main">Rumah Buku Fasilkom UI</h1>
            </div>

            <div class="border-line-sub"></div>

            <div class="container mx-auto d-block" style="margin: 20px;">
                <div class="row">
                    <div class="col">
                        <img class="rumbuk-image" src="{% static 'images/jumbotronRUMBUK-01.png' %}" alt="rumbuk-logo" width="400px" height="300px" style="border-radius: 30px;">
                    </div>
                    <div class="col project-desc">
                        <p>Library website for FUKI Fasilkom UI.</p>
                        <p>I worked as...</p>
                        <p><em><u>Product Owner</u></em></p>
                        <p><em><u>Back-End Developer</u></em></p>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</html>

story_5/templates/schedule-form.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    {% block title %}
        Farhan Azmi - My Schedule Form
    {% endblock %}
</head>

<body>
    {% block content %}
        <div class="main-div">
            <div>
                <h1 class="text-main">Form Jadwal kegiatan</h1>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block" action="{% url 'schedule:schedule-form' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form }}
                    </div>
                    <button type="submit" class="btn btn-primary">Input Jadwal Kegiatan</button>
                </form>
            </div>
        </div>
    {% endblock %}
</body>

story_5/templates/schedule-list.html
{% extends 'layout/base.html' %}
<!DOCTYPE HTML>
{% block title %}
    Farhan Azmi - Daftar Jadwal
{% endblock title %}

{% block content %}
    <div class="main-div">
        <div>
            <h1 class="text-main">Data Jadwal kegiatan</h1>
        </div>

        <div class="container mx-auto d-block">
            {% if schedule %}
                <table class="table table-hover table-striped table-dark" align="center" style="text-align: center">
                    <thead>
                        <tr>
                            <th scope="col">Nama Kegiatan</th>
                            <th scope="col">Tempat Kegiatan</th>
                            <th scope="col">Kategori Kegiatan</th>
                            <th scope="col">Jadwal kegiatan</th>
                        </tr>
                    </thead>
                    {% for data in schedule %}
                        <tr>
                            <td scope="row">{{ data.name }}</td>
                            <td scope="row">{{ data.place }}</td>
                            <td scope="row">
                                {% if data.category %}
                                    {{ data.category }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td scope="row">
                                {{ data.time|date:"l" }}, {{ data.time }}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <form action="{% url 'schedule:schedule-delete' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit" style="margin-bottom: 10px">Hapus Semua Kegiatan</button>
                </form>
            {% else %}
                <h1 class="text-main">Tidak Ada Jadwal Kegiatan</h1>
            {% endif %}


            <button class="btn btn-info btn-primary" style="margin-bottom: 10px">
                <a href="{% url 'schedule:schedule-form' %}">Kembali ke Form</a>
            </button>
        </div>
    </div>
{% endblock content %}